<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="comicshop" nsURI="comicshop" nsPrefix="comicshop">
  <eClassifiers xsi:type="ecore:EClass" name="Shop">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="comics" nsURI="comics" nsPrefix="">
    <eSubpackages name="toys" nsURI="toys" nsPrefix="">
      <eClassifiers xsi:type="ecore:EClass" name="PowerRanger">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="merchandising" nsURI="merchandising" nsPrefix=""/>
</ecore:EPackage>
